const classes = JSON.stringify([
      'pre nursery ',
      'pre nursery new admission',
      'pre nursery mercury',
      'pre nursery venus',
      'nursery 1',
      'nursery 1 new admission',
      'nursery 1 mercury',
      'nursery 1 venus',
      'nursery 1 mars',
      'nursery 2',
      'nursery 2 new admission',
      'nursery 2 mercury',
      'nursery 2 venus',
      'nursery 2 mars',
      'nursery 2 jupiter',
      'kindergaten 3',
      'kindergaten 3 new admission',
      'kindergaten 3 mercury',
      'kingergaten 3 venus',
      'kingergaten 3 mars',
      'kingergaten 3 jupiter',
      'kingergaten 3 earth',
      'basic 1',
      'basic 1 new admission',
      'basic 1 mercury',
      'basic 1 venus',
      'basic 1 mars',
      'basic 1 jupiter',
      'basic 2 mercury',
      'basic 2',
      'basic 2 new admission',
      'basic 2 venus',
      'basic 2 mars',
      'basic 2 jupiter',
      'basic 2 earth',
      'basic 3',
      'basic 3 new admission',
      'basic 3 mercury',
      'basic 3 venus',
      'basic 3 mars',
      'basic 4',
      'basic 4 new admission',
      'basic 4 mercury',
      'basic 4 venus',
      'basic 4 mars',
      'basic 4 jupiter',
      'basic 5',
      'basic 5 new admission',
      'basic 5 mercury',
      'basic 5 venus',
      'basic 5 mars',
      'basic 6',
      'jss 1',
      'jss 1 new admission',
      'jss 1 mercury',
      'jss 1 venus',
      'jss 1 mars',
      'jss 1 jupiter',
      'jss 2',
      'jss 2 new admission',
      'jss 2 mercury',
      'jss 2 venus',
      'jss 2 mars',
      'jss 2 jupiter',
      'jss 3',
      'jss 3 new admission',
      'jss 3 mercury',
      'jss 3 venus',
      'jss 3 mars',
      'jss 3 jupiter',
      'ss 1',
      'ss 1 new admission',
      'ss 1 mercury',
      'ss 1 venus',
      'ss 1 mars',
      'ss 1 jupiter',
      'ss 2',
      'ss 2 new admission',
      'ss 2 mercury',
      'ss 2 venus',
      'ss 2 mars',
      'ss 2 jupiter',
      'ss 3',
      'ss 3 new admission',
      'ss 3 mercury',
      'ss 3 venus',
      'ss 3 mars',
      'ss 3 jupiter',
  ])
const fees = JSON.stringify({
    pre_nursery:60500,
    nursery:63500,
    kindergaten:66500,
    basic:63500,
    basic_6:66500,
    jss:70500,
    ss:72500,
  })

module.exports = {
    classes,
    fees
};
